#!/bin/bash

# Manual Azure PostgreSQL Setup Guide
# Run these commands step by step

echo "🔧 Manual Azure PostgreSQL Setup Commands"
echo "==========================================="
echo ""
echo "1. Login to Azure:"
echo "   az login"
echo ""
echo "2. Create Resource Group:"
echo "   az group create --name django-backend-rg --location \"Central India\""
echo ""
echo "3. Create PostgreSQL Flexible Server:"
echo "   az postgres flexible-server create \\"
echo "     --resource-group django-backend-rg \\"
echo "     --name your-postgres-server \\"
echo "     --location \"Central India\" \\"
echo "     --admin-user postgres \\"
echo "     --admin-password \"YourSecurePassword123!\" \\"
echo "     --sku-name Standard_B1ms \\"
echo "     --tier Burstable \\"
echo "     --storage-size 32 \\"
echo "     --version 15 \\"
echo "     --public-access 0.0.0.0-255.255.255.255"
echo ""
echo "4. Create Database:"
echo "   az postgres flexible-server db create \\"
echo "     --resource-group django-backend-rg \\"
echo "     --server-name your-postgres-server \\"
echo "     --database-name django_db"
echo ""
echo "5. Add Firewall Rule for Azure Services:"
echo "   az postgres flexible-server firewall-rule create \\"
echo "     --resource-group django-backend-rg \\"
echo "     --name your-postgres-server \\"
echo "     --rule-name \"AllowAzureServices\" \\"
echo "     --start-ip-address 0.0.0.0 \\"
echo "     --end-ip-address 0.0.0.0"
echo ""
echo "6. Add Firewall Rule for Your IP:"
echo "   az postgres flexible-server firewall-rule create \\"
echo "     --resource-group django-backend-rg \\"
echo "     --name your-postgres-server \\"
echo "     --rule-name \"AllowMyIP\" \\"
echo "     --start-ip-address YOUR_IP \\"
echo "     --end-ip-address YOUR_IP"
echo ""
echo "7. Get your current IP:"
echo "   curl https://ipinfo.io/ip"
echo ""
echo "📝 Connection String Format:"
echo "postgresql://postgres:YourSecurePassword123!@your-postgres-server.postgres.database.azure.com:5432/django_db?sslmode=require"
echo ""
echo "💰 Estimated Cost: \$15-25/month for Standard_B1ms"
echo ""
echo "🗑️ To delete everything:"
echo "az group delete --name django-backend-rg --yes --no-wait"
