version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      # Use your actual Azure PostgreSQL credentials (URL-encoded password)
      - DATABASE_URL=postgresql://postgres:Test%40123@django-postgres-server-1755601473.postgres.database.azure.com:5432/django_db?sslmode=require
    # No local db dependency since we're using Azure PostgreSQL

# Note: Local PostgreSQL service removed since we're using Azure PostgreSQL
# If you want to test with local PostgreSQL, uncomment the section below:
#
#  db:
#    image: postgres:15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_DB=myproject
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
#
# volumes:
#   postgres_data:
